import { canRestoreOrigin } from '../origin/canRestoreOrigin';
import { parseParameterLines } from '../origin/parseParameterLines';
import type { ParameterOffset, RestoreGuardState } from '../origin/types';
import type { RunProbeDeps, RunProbeResult } from './types';

const toNumber = (value: string): number => Number.parseFloat(value) || 0;

const isOffsetNonZero = (offset: ParameterOffset): boolean =>
    toNumber(offset.x) !== 0 ||
    toNumber(offset.y) !== 0 ||
    toNumber(offset.z) !== 0;

const DEFAULT_SETTLE_TIMEOUT_MS = 60_000;

// G38.2 can legitimately run for as long as the configured search distance
// takes to traverse at the slow feedrate -- Grbl itself withholds "ok" until
// the probe cycle ends (contact or ALARM), so a per-line query timeout has
// to outlast that, not just network/parse latency.
const PROBE_LINE_TIMEOUT_MS = 65_000;

// Grbl answers a failed G38.2 with "ALARM:n", not "error:n" -- the default
// query() terminator (ok-or-error) would never match it, so the capture
// would sit uselessly until its own timeout before the (already-correct)
// line data got through. Recognizing ALARM here lets a probe failure abort
// the sequence immediately instead of stalling on every failed probe.
const TERMINATOR_PATTERN = /^(ok|error:\s*\d+|ALARM:\s*.+)$/;
const ALARM_CODE_PATTERN = /^ALARM:\s*(\d+)/;

const findAlarmCode = (lines: string[]): number | undefined => {
    for (const line of lines) {
        const match = line.match(ALARM_CODE_PATTERN);
        if (match) {
            return Number(match[1]);
        }
    }
    return undefined;
};

/**
 * Sends every line through `query()`, one at a time, awaiting Grbl's actual
 * response before the next line goes out.
 *
 * T8 real-machine finding (Zのみプローブ: "検証の$#応答にG54の行がありませんでした"
 * -- the same symptom as restoreOrigin.ts's ORIGIN_MISMATCH with X0 Y0 Z0):
 * mixing a feeder-queued gcode batch (`machine.command`, resolves on
 * delivery only) with a separately-issued direct verify `query()` let a
 * stray "ok" meant for the batch get consumed by the verify's own capture
 * window instead, sometimes losing the G54 line entirely. Routing the whole
 * sequence through query() keeps everything on the one channel that
 * actually waits for Grbl, line by line, so no response can ever be
 * ambiguous about which write it belongs to -- exactly the fix already
 * applied to restoreOrigin.ts.
 *
 * `waitForSettle` (Idle+G90, driven off live redux status reports) is kept
 * as-is afterward: per-line query() only proves Grbl accepted every line in
 * protocol order, not that a buffered-ack move (e.g. the final retract) has
 * physically finished, so it still earns its keep as the real completion
 * gate before reading G54 back.
 */
const sendProbeLinesSequentially = async (
    query: RunProbeDeps['query'],
    lines: string[],
): Promise<number | undefined> => {
    for (const line of lines) {
        const response = await query(line, {
            until: TERMINATOR_PATTERN,
            timeout: PROBE_LINE_TIMEOUT_MS,
        });
        const alarmCode = findAlarmCode(response.lines);
        if (alarmCode !== undefined) {
            return alarmCode;
        }
    }
    return undefined;
};

/**
 * Shared orchestration for all three probe kinds (XYZ/XY/Z): same guard,
 * G92 detection/confirm, busy flag, and settle wait -- only the gcode
 * `lines` (already generated by generateProbeGcode / generateZOnlyProbeGcode)
 * differ per call site.
 */
export const runProbe = async (
    lines: string[],
    guard: RestoreGuardState,
    deps: RunProbeDeps,
    settleTimeoutMs = DEFAULT_SETTLE_TIMEOUT_MS,
): Promise<RunProbeResult> => {
    const guardResult = canRestoreOrigin(guard);
    if (!guardResult.allowed) {
        return { outcome: 'BLOCKED', reason: guardResult.reason };
    }

    const before = await deps.query('$#');
    const beforeParams = parseParameterLines(before.lines);

    if (beforeParams.G92 && isOffsetNonZero(beforeParams.G92)) {
        const approved = await deps.confirmClearG92();
        if (!approved) {
            return { outcome: 'CANCELLED', reason: 'G92のクリアが承認されませんでした。' };
        }
        await deps.query('G92.1');
    }

    await deps.setBusy(true, 'プローブ中');
    try {
        const alarmCode = await sendProbeLinesSequentially(deps.query, lines);
        if (alarmCode !== undefined) {
            return { outcome: 'ALARM', code: alarmCode };
        }

        const settled = await deps.waitForSettle(settleTimeoutMs);
        if (!settled) {
            return { outcome: 'TIMEOUT' };
        }

        const after = await deps.query('$#');
        const { G54 } = parseParameterLines(after.lines);
        return { outcome: 'DONE', g54: G54 };
    } finally {
        await deps.setBusy(false);
    }
};
