import { canRestoreOrigin } from '../origin/canRestoreOrigin';
import { parseParameterLines } from '../origin/parseParameterLines';
import type { ParameterOffset, RestoreGuardState } from '../origin/types';
import type { RunProbeDeps, RunProbeResult } from './types';

const toNumber = (value: string): number => Number.parseFloat(value) || 0;

const isOffsetNonZero = (offset: ParameterOffset): boolean =>
    toNumber(offset.x) !== 0 ||
    toNumber(offset.y) !== 0 ||
    toNumber(offset.z) !== 0;

const DEFAULT_SETTLE_TIMEOUT_MS = 60_000;

/**
 * Shared orchestration for all three probe kinds (XYZ/XY/Z): same guard,
 * G92 detection/confirm, busy flag, and settle wait as T3's restoreOrigin --
 * only the gcode `lines` (already generated by generateProbeGcode /
 * generateZOnlyProbeGcode) differ per call site.
 */
export const runProbe = async (
    lines: string[],
    guard: RestoreGuardState,
    deps: RunProbeDeps,
    settleTimeoutMs = DEFAULT_SETTLE_TIMEOUT_MS,
): Promise<RunProbeResult> => {
    const guardResult = canRestoreOrigin(guard);
    if (!guardResult.allowed) {
        return { outcome: 'BLOCKED', reason: guardResult.reason };
    }

    const before = await deps.query('$#');
    const beforeParams = parseParameterLines(before.lines);

    if (beforeParams.G92 && isOffsetNonZero(beforeParams.G92)) {
        const approved = await deps.confirmClearG92();
        if (!approved) {
            return { outcome: 'CANCELLED', reason: 'G92 clear was not approved.' };
        }
        await deps.sendGcode(['G92.1']);
    }

    await deps.setBusy(true, 'Probing');
    try {
        await deps.sendGcode(lines);

        const settled = await deps.waitForSettle(settleTimeoutMs);
        if (!settled) {
            return { outcome: 'TIMEOUT' };
        }

        const after = await deps.query('$#');
        const { G54 } = parseParameterLines(after.lines);
        return { outcome: 'DONE', g54: G54 };
    } finally {
        await deps.setBusy(false);
    }
};
